import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    DATABASE_URL: z.url(),
    AUTH_SECRET: z.string().min(32).max(128),
    AUTH_GITHUB_ID: z.string().min(2).max(128),
    AUTH_GITHUB_SECRET: z.string().min(2).max(128),
    AUTH_GOOGLE_ID: z.string().min(2).max(128),
    AUTH_GOOGLE_SECRET: z.string().min(2).max(128),
    REDIS_URL: z.url(),
    GROQ_API_KEY: z.string().min(2).max(128),
    GEMINI_API_KEY: z.string().min(2).max(128).optional(),
    RESEND_API_KEY: z.string().min(2).max(128).optional(),
    RESEND_FROM: z.string().min(1).optional(),
    RAZORPAY_KEY_ID: z.string().min(2).max(128).optional(),
    RAZORPAY_KEY_SECRET: z.string().min(2).max(128).optional(),
    RAZORPAY_WEBHOOK_SECRET: z.string().min(2).max(128).optional(),
    RAZORPAY_PRO_MONTHLY_PLAN_ID: z.string().min(2).max(128).optional(),
    CLOUDINARY_CLOUD_NAME: z.string().min(2).max(128),
    CLOUDINARY_API_KEY: z.string().min(2).max(128),
    CLOUDINARY_API_SECRET: z.string().min(2).max(128),
    APP_URL: z.url(),
  },
  client: {},
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    AUTH_SECRET: process.env.AUTH_SECRET,
    AUTH_GITHUB_ID: process.env.AUTH_GITHUB_ID,
    AUTH_GITHUB_SECRET: process.env.AUTH_GITHUB_SECRET,
    AUTH_GOOGLE_ID: process.env.AUTH_GOOGLE_ID,
    AUTH_GOOGLE_SECRET: process.env.AUTH_GOOGLE_SECRET,
    REDIS_URL: process.env.REDIS_URL,
    GROQ_API_KEY: process.env.GROQ_API_KEY,
    GEMINI_API_KEY: process.env.GEMINI_API_KEY,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    RESEND_FROM: process.env.RESEND_FROM,
    RAZORPAY_KEY_ID: process.env.RAZORPAY_KEY_ID,
    RAZORPAY_KEY_SECRET: process.env.RAZORPAY_KEY_SECRET,
    RAZORPAY_WEBHOOK_SECRET: process.env.RAZORPAY_WEBHOOK_SECRET,
    RAZORPAY_PRO_MONTHLY_PLAN_ID: process.env.RAZORPAY_PRO_MONTHLY_PLAN_ID,
    CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
    APP_URL: process.env.APP_URL,
  },
});
